### PR TITLE
Update README with locally-hosted MX instructions

### LINKED ISSUE #70: Forum is dropping emails
For the last few weeks we've been intermittently missing forum notifications from https://forum.spinalcordmri.org. Some people will receive them, some won't.

@alexfoias discovered it was a problem with spam filters suddenly getting picky about our forum emails. @joshuacwnewton discovered the problem is that SendGrid, the SMTP-as-a-Service that we're using, has been under attack? pressure? I don't know what you'd call it. Anyway here's the story: https://krebsonsecurity.com/2020/08/sendgrid-under-siege-from-hacked-accounts/. As a result, several (but not all!) of their free-tier servers are now on spamlists, e.g. https://talosintelligence.com/reputation_center/lookup?search=167.89.100.223 or https://www.spamhaus.org/sbl/query/SBL499109. This explains why the problem is intermittent.

### PR DESCRIPTION
**Pull request by kousu**
Integrate the instructions from #70 into the main instructions.

Also make sure to make explicit that these are for Ubuntu 18.04-LTS. When we do #71, we should make sure to change that and re-adapt all the instructions for the new platform.

Closes #70.

### CODE REVIEW

**Comment by kousu** [comment]
The one weird thing about these is that they require running `./discourse-setup` twice, and I haven't tested if, in the first run, you're even allowed to skip entering SMTP credentials, or if skipping that will break the forum by preventing the admins from getting their initial accounts.

I am not going to test on the real server lest I break it. I also don't really feel like setting up a whole server from scratch just to validate these instructions start to finish, though I probably should.

**Comment by kousu** [comment]
@jcohenadad or @alexfoias can you give these email server instructions a once over? I have misgivings about it being written for an outdated ubuntu and about not actually getting to properly test it. We could test these instructions if we had a temporary spare VM to try things out on, and remembered to substitute a different domain name everywhere.

**Comment by alexfoias** [comment]
@kousu The instructions seem clear to me. I was involved only in the changes for namecheap, so I cannot verify the accuration of the other steps. As you said, best way to validate it is to test it on a VM.

**Comment by kousu** [comment]
I propose that we can probably figure out any bugs in the docs if we need to use them again. Maintaining the forum isn't a core part of what the team is doing. In the interests of time how about this: give me an Approval, we'll merge this, and then when we do #71 we do it by rebuilding the server on a new VM from backups; at that point we'll be able to catch any bugs in the docs. We'll need to update them anyway to account for the minor shifts in the OS anyway.

**Comment by jcohenadad** [comment]
As @alexfoias said, the instructions look clear to me, but the best way to assess them is to try them. So as @kousu  suggested, someone else (e.g. Alex) could setup the forum on the new VM using those instructions and raise issues/clarifications-needed along the way

**Comment by jcohenadad** [comment]
I should also add: thank you very much for putting together those instruction! 🙏

**Review by jcohenadad — APPROVED** [review]
yay! 🎉

**Pull request merged**
