### PR TITLE
I would like to add the 2nd spinal cord workshop at UCL

### PR DESCRIPTION
**Pull request by fprados**
It is a preliminar webpage, but we can start to circulate it.

### CODE REVIEW

**Comment by jcohenadad** [comment]
@fprados I just merged it, but realized that we might want to start changing the numbering of this event. I find it a bit confusing to see "2nd workshop" at the top of the list, followed by "6th workshop". 

Since we are converging towards not having SC workshops after ISMRM anymore, we might want to consider this workshop the "official" SC workshop, and hence calling this workshop "7th Spinal Cord MRI Workshop". What do you think?

**Comment by fprados** [comment]
Dear @jcohenadad , this is up to you. Last year, we had the same conversation but in the other way.

**Comment by jcohenadad** [comment]
> Dear @jcohenadad , this is up to you. Last year, we had the same conversation but in the other way.

yup i know-- but as i mentioned, things are changing. It looks like we are now converging towards  **not** having sc workshops after ismrm, the london one being "the" workshop-- so i think it makes sense to change it to 7th workshop. would you mind please doing this small change? many thanks!

**Comment by jcohenadad** [comment]
@fprados no worries i've updated the title

**Pull request merged**
