### PR TITLE
added Beijing workshop

### PR DESCRIPTION
**Pull request by alexfoias**

### CODE REVIEW

**Comment by alexfoias** [comment]
@jcohenadad We didn't push this one yet.

**Comment by jcohenadad** [comment]
Thank you for the reminder @alexfoias-- let me do a few adjustments and we can merge

**Comment by jcohenadad** [comment]
@alexfoias could you please create a branch within this repos so i can easily modify? thanks

**Comment by alexfoias** [comment]
@jcohenadad Yes sure. I don't think I have write permissions on the repo when trying to push on a new brach. I receive this message: 
```
remote: Permission to spinalcordmri/spinalcordmri.github.io.git denied to alexfoias.
```

**Comment by jcohenadad** [comment]
> @jcohenadad Yes sure. I don't think I have write permissions on the repo when trying to push on a new brach. I receive this message:
> 
> ```
> remote: Permission to spinalcordmri/spinalcordmri.github.io.git denied to alexfoias.
> ```

strange, you are an admin:

Screen Shot 2019-10-03 at 12 05 17 PM

**Comment by alexfoias** [comment]
Closing the PR. The beijing course will be added by https://github.com/spinalcordmri/spinalcordmri.github.io/pull/41

**Pull request closed without merging**
