### PR TITLE
Update logo url for philips

### PR DESCRIPTION
**Pull request by fprados**

### CODE REVIEW

**Comment by fprados** [comment]
I've request again because I see that it doesn't appear

**Comment by alexfoias** [comment]
I addressed this problem in the PR https://github.com/spinalcordmri/spinalcordmri.github.io/pull/53

**Comment by fprados** [comment]
@alexfoias really thanks but the filename needs to have - instead than _ 

http://www.spinalcordmri.org/assets/2020-01-20-workshop/philips-logo.png

**Comment by fprados** [comment]
Thanks @alexfoias

**Pull request merged**
