### PR TITLE
add logo Siemens for 7th spinal cord workshop

### PR DESCRIPTION
**Pull request by alexfoias**

### CODE REVIEW

**Comment by alexfoias** [comment]
It renders well. here is the screenshot:

Screen Shot 2019-12-13 at 11 45 32 AM

**Comment by jcohenadad** [comment]
great! but now there is a conflict ;-)

**Comment by alexfoias** [comment]
@jcohenadad I fixed the conflict

**Comment by alexfoias** [comment]
fixed

**Pull request merged**
